<?php return array (
  'Img4Web\\Plugin' => '/includes/Plugin.php',
  'Img4Web\\Vendor\\PiotrPress\\WordPress\\Notice' => '/vendor/piotrpress/wordpress-notice/src/Notice.php',
  'Img4Web\\Image' => '/includes/Image.php',
  'Img4Web\\Command' => '/includes/Command.php',
  'Img4Web\\Vendor\\PiotrPress\\WordPress\\Plugin' => '/vendor/piotrpress/wordpress-plugin/src/Plugin.php',
  'Img4Web\\Vendor\\PiotrPress\\Singleton' => '/vendor/piotrpress/singleton/src/Singleton.php',
  'Img4Web\\Vendor\\PiotrPress\\Templater' => '/vendor/piotrpress/templater/src/Templater.php',
  'Img4Web\\Vendor\\PiotrPress\\TemplaterInterface' => '/vendor/piotrpress/templater/src/TemplaterInterface.php',
  'Img4Web\\Vendor\\PiotrPress\\WordPress\\Hooks\\Action' => '/vendor/piotrpress/wordpress-hooks/src/Action.php',
  'Img4Web\\Vendor\\PiotrPress\\WordPress\\Hooks' => '/vendor/piotrpress/wordpress-hooks/src/Hooks.php',
  'Img4Web\\Vendor\\PiotrPress\\WordPress\\Hooks\\Filter' => '/vendor/piotrpress/wordpress-hooks/src/Filter.php',
  'Img4Web\\Vendor\\PiotrPress\\CacheInterface' => '/vendor/piotrpress/cacher/src/CacheInterface.php',
  'Img4Web\\Vendor\\PiotrPress\\Cacher' => '/vendor/piotrpress/cacher/src/Cacher.php',
  'Img4Web\\Vendor\\PiotrPress\\Logger' => '/vendor/piotrpress/logger/src/Logger.php',
  'Img4Web\\Vendor\\Psr\\Log\\LoggerAwareTrait' => '/vendor/psr/log/Psr/Log/LoggerAwareTrait.php',
  'Img4Web\\Vendor\\Psr\\Log\\NullLogger' => '/vendor/psr/log/Psr/Log/NullLogger.php',
  'Img4Web\\Vendor\\Psr\\Log\\AbstractLogger' => '/vendor/psr/log/Psr/Log/AbstractLogger.php',
  'Img4Web\\Vendor\\Psr\\Log\\LoggerTrait' => '/vendor/psr/log/Psr/Log/LoggerTrait.php',
  'Img4Web\\Vendor\\Psr\\Log\\LoggerInterface' => '/vendor/psr/log/Psr/Log/LoggerInterface.php',
  'Img4Web\\Vendor\\Psr\\Log\\InvalidArgumentException' => '/vendor/psr/log/Psr/Log/InvalidArgumentException.php',
  'Img4Web\\Vendor\\Psr\\Log\\LogLevel' => '/vendor/psr/log/Psr/Log/LogLevel.php',
  'Img4Web\\Vendor\\Psr\\Log\\LoggerAwareInterface' => '/vendor/psr/log/Psr/Log/LoggerAwareInterface.php',
); # This file is part of https://github.com/PiotrPress/composer-classmapper package.